jg10545/patchwork

.gitignore, patchwork/_deepcluster.py, patchwork/_labeler.py, patchwork/_layers.py, patchwork/_loaders.py, patchwork/_losses.py, patchwork/_main.py, patchwork/_modelpicker.py, patchwork/_models.py, patchwork/_sample.py, patchwork/_trainmanager.py, patchwork/_util.py
* multi-hot encoding for non-disjoint classes
* masked loss functions can handle partially missing labels
* `gdal` wrapper for loading TIFF files
* can run with pre-extracted features or a "live" fully-convolutional feature extractor
* `tf.data` backend for live case
* some very basic plots for telling what the hell you're doing
* just a few simple models- lots of room to improve, and `baseline++` may need some modification to make sense for multihot categories.
Still need to add unit tests, add more documentation, and revisit/clean up code for self-supervised learning.
=> Anothernewgui

patchwork/_augment.py, patchwork/feature/_generic.py, patchwork/feature/_simclr.py, patchwork/feature/_simclr_multi.py, patchwork/tests/test_feature_simclr.py
really just some tiny changes here
=> Simclrupdates

patchwork/_output_models.py, patchwork/feature/_autoencoder.py, patchwork/feature/_contextencoder.py, patchwork/feature/_deepcluster.py, patchwork/feature/_generic.py, patchwork/feature/_multitask.py, patchwork/feature/_simclr.py, patchwork/feature/_simclr_multi.py, patchwork/tests/test_feature_contextencoder.py, patchwork/tests/test_feature_deepcluster.py, patchwork/tests/test_feature_simclr.py
=> Featurecleanup

patchwork/stateless.py, patchwork/tests/test_stateless.py
this way the UI doesn't have to do any custom formatting, so we can experiment with different measures without having to update any code in the UI
=> return val measures as strings

patchwork/feature/_simclr.py, patchwork/loaders.py, patchwork/tests/test_feature_simclr.py, patchwork/tests/test_loaders.py
Integrated with `pw.loaders.dataset()` and `pw.feature.SimCLRTrainer()`
=> first shot at enabling custom datasets

patchwork/feature/_generic.py, patchwork/tests/test_viz_projector.py, patchwork/viz/__init__.py, patchwork/viz/_projector.py
Added a method to the generic feature extractor trainer class to save projections from the `labeldict`.
=> Tensorboard projector visualization

patchwork/_badge.py
In some real-data tests using the active learning GUI, this version was about three times faster.
=> rewrote badge sampler

README.md, docs/feature.md, patchwork/feature/__init__.py, patchwork/feature/_deepcluster.py, patchwork/feature/_generic.py, patchwork/feature/_moco.py, patchwork/feature/_simclr.py, patchwork/tests/test_feature_moco.py
When SimCLR came out I thought it rendered MoCo obsolete, but the MoCoV2 paper makes some good points about hardware requirements. Definitely worth dusting off and fixing the problems with my implementation.
=> un-deprecating momentum contrast

patchwork/_tasks.py, patchwork/feature/_generic.py, patchwork/feature/_rotation.py, patchwork/loaders.py, patchwork/tests/test_feature_rotation.py, patchwork/tests/test_loaders.py, patchwork/tests/test_tasks.py
Added a feature extractor trainer based on rotation prediction, as well as rotation prediction as a proxy task for evaluating any trainer.
=> Rotationtask

docs/input_aug.md, patchwork/_augment.py, patchwork/tests/test_augment.py
* modified version of rescaling function, biased toward center of image
* jpeg degradation
=> new augmentation methods

patchwork/_augment.py, patchwork/feature/_autoencoder.py, patchwork/feature/_contextencoder.py, patchwork/feature/_deepcluster.py, patchwork/feature/_detcon.py, patchwork/feature/_generic.py, patchwork/feature/_hcl.py, patchwork/feature/_moco.py, patchwork/feature/_multitask.py, patchwork/feature/_simclr.py, patchwork/viz/_feature.py
rewrote hcl/detcon so that number of graph operations doesn't change with batch size
=> Detcon mask

patchwork/_tfrecord.py, patchwork/feature/_clip.py, patchwork/feature/_moco.py, patchwork/feature/_simclr.py, patchwork/loaders.py, patchwork/tests/test_feature_moco.py, patchwork/tests/test_feature_simclr.py, patchwork/tests/test_tfrecord.py
prototype capability for training SimCLR, MoCo, or HCL using a custom dataset that returns pairs of images.
=> Contrastivepairs

patchwork/_labeler.py, patchwork/_main.py, patchwork/_sample.py, patchwork/tests/test_labeler.py, patchwork/tests/test_sample.py
* closes #123 
* closes #121 
* closes #119 
* closes #117 
* closes #120 
* closes #118
=> Guiupdates

patchwork/_labeler.py, patchwork/_main.py, patchwork/_modelpicker.py, patchwork/_training_functions.py, patchwork/_trainmanager.py, patchwork/_util.py, patchwork/tests/test_training_functions.py
* "all zeros" labeling option
* "copy labels" labeling option
* option to end training early if test loss stalls
* compatibility with `tf.distribute`
=> adding more functionality to GUI

patchwork/_labeler.py, patchwork/_main.py, patchwork/_modelpicker.py, patchwork/_resnet.py, patchwork/_training_functions.py, patchwork/_trainmanager.py, patchwork/_util.py, patchwork/feature/_generic.py, patchwork/feature/_simclr.py, patchwork/loaders.py, patchwork/tests/test_training_functions.py
support for mixed-precision training in SimCLR and improvements to GUI
=> Mixedprecision

patchwork/__init__.py, patchwork/_distill.py, patchwork/feature/_generic.py, patchwork/tests/test_distill.py
improved tools for distillation of models
=> Distillchanges

README.md, docs/feature.md, patchwork/_distill.py, patchwork/_util.py, patchwork/feature/_generic.py, patchwork/feature/_moco.py, patchwork/feature/_nnclr.py, patchwork/feature/_simclr.py, patchwork/feature/_vicreg.py, patchwork/tests/test_feature_moco.py, patchwork/tests/test_util.py
current version runs on multiple GPUs but doesn't support shuffle/deshuffle operations to prevent batch norm-related shortcuts
=> Mocochanges

patchwork/feature/_contrastive.py, patchwork/tests/test_feature_contrastive.py
Dramatically speeds up autograph tracing for SimCLR on multiple GPUs
=> copying over mike's amazing fix

setup.py
=> MIKE'S AMAZING FIX

patchwork/_eval.py, patchwork/tests/test_eval.py, patchwork/viz/_eval.py
improvements to `pw.sample_and_evaluate()`
=> Evalupdates
